version: '2'
services:
  back:
    container_name: bucket.back
    build: ./back
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app
    dns: 
      - '8.8.8.8'
      - '8.8.4.4'
    networks:
      - bucket-net

  front:
    container_name: bucket.front
    build: ./front
    env_file: 
      - ./front/.env
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
    dns: 
      - '8.8.8.8'
      - '8.8.4.4'
    networks:
      - bucket-net
      
networks:
  bucket-net:
    external: true